### ISSUE TITLE
Failed to open i2c port

### ISSUE THREAD

**Issue by adenbeckitt** [Manawyrm/FMBerry#16]
I built it with RPI_REVISION RPI_REV1
Wiring is correct.
i2cdetect -y 0 shows;

```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- 66 -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```

However, when running the daemon I get "Failed to open i2c port"
Log says "Init failed! Double-check hardware and try again!"

Any ideas?

**Comment by adenbeckitt** [comment]
Adding dtparam=i2c_vc=on to /boot/config.txt stops the daemon saying "Failed to open i2c port" but I still get Init failed on the log.

**Comment by adenbeckitt** [comment]
I had to change i2cbus = 1 to i2cbus = 0 in the conf. :)

**Comment by Manawyrm** [comment]
Brilliant 👍 

Have fun with the transmitter!
